---
driver_plugin: docker

platforms:
- name: ubuntu
  driver_config:
    provision_command:
      - "curl -L https://www.opscode.com/chef/install.sh | sudo bash"
    require_chef_omnibus: false
  run_list:
  - recipe[apt]
  - recipe[logrotate]

suites:
- name: default
  run_list:
  - recipe[monitor::master]
