---
driver_plugin: docker

platforms:
- name: ubuntu
  driver_config:
    provision_command:
      - "curl -L https://www.opscode.com/chef/install.sh | sudo bash"
    require_chef_omnibus: false
  run_list:
  - recipe[apt]
  - recipe[logrotate]

suites:
- name: default
  run_list:
  - recipe[monitor::master]
- name: haproxy
  run_list:
    - recipe[haproxy]
    - recipe[monitor::master]
    - recipe[monitor::haproxy]
  attributes:
    sensu:
      dashboard:
        port: 4000
    haproxy:
      enable_stats_socket: true
    monitor:
      additional_client_attributes:
        haproxy_services: "servers-http"
